### PR TITLE
React v0.13 and Opal 0.8

### PR DESCRIPTION
**Pull request by wied03**
This is not meant to be a final pull request (just a discussion kickoff).

The main fixes I made here are:
- Adapt to native_alias changes
- Made tests that alter console.log a bit more robust
- Build on ext/string work that someone else already noted

I had to try and fix an issue in Opal itself and that pull request is pending. In order to use my draft/fixed code, this project is currently pointing at my forks of opal and opal-rspec.

Anyways, hopefully this helps with talking about migration approaches, etc.

### CODE REVIEW

**Comment by zetachang** [comment]
Hi, I've tried out your changes today, the stack trace formatter doesn't work well for me either in browser or CLI? In browser, it logs directly to console, and in CLI, the test log is duplicated. 

Also, I've notice the opal-spec specified (your forked version) are even with the original source, is there anything I missed?

Besides, everything looks fine to me, I will cherry pick them in when next beta of opal 0.8 came out. :+1:

**Comment by wied03** [comment]
Yeah, I'm not sure why those issues are happening.

The opal project accepted the pull request so no fork needed there. Opal-rspec has not accepted it yet, so still pointing at my branch for now. Hopefully some of this helps.

I'm also trying to work on getting RSpec 3.1 working with Opal. It seems a shame to be stuck an 3.0 (and a beta of 3.0, not the final version).

**Comment by wied03** [comment]
Another problem I'm seeing here is that react.rb ends up inadvertently defining a top level Element class (in addition to the React::Element class). This conflicts with opal-jquery and makes opal-jq pretty much unusable.

I added a test to try and verify this is fixed and I tried to format the js code in element.rb better. I'm not quite proficient enough in JS at the moment to understand what that code is doing, but it looks like you're cleverly trying to make the React Element objects that React itself produces inherit from this class. This just seems to be a side effect.

**Comment by wied03** [comment]
Created issue https://github.com/zetachang/react.rb/issues/36

**Comment by wied03** [comment]
FYI, these Travis builds are failing because of git submodule stuff and the way that I tweaked opal-rspec

**Comment by wied03** [comment]
the travis.yml/submodule approach is not permanent, but at least it lets this build work properly until something happens with opal-rspec

**Comment by zetachang** [comment]
I failed to checkout `9098ea05a463c8e9a59b254d4381dc4c61873d95` on your own opal-rspec fork. :worried:

**Comment by wied03** [comment]
@zetachang Sorry about that. They're working on making a branch from my PR over there and I squashed the commits. As a result, that old commit is gone. Just pushed a new one out there

**Comment by wied03** [comment]
@zetachang - Any word here? Opal 0.8 was released several weeks ago and they/we also have an opal-rspec beta published to rubygems that works with it and gets RSpec to 3.1 (working more on that project as we speak).

I'm happy to get this PR up to date with that if you want to move that way.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#31

**Pull request closed without merging**
