### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by maxdignan**
'localhost' typo on line 86

### CODE REVIEW

**Comment by ajjahn** [comment]
Thanks!

**Comment by maxdignan** [comment]
Np... Awesome project you all have here - I just stumbled upon it yesterday!

**Comment by ajjahn** [comment]
Glad you like it. Now you're a contributor, so... Keep up the good work!

**Comment by catmando** [comment]
Max,

welcome aboard!

Mitch VanDuyn
Founder - Catprint.com LLC
The New Approach to Color Printing
585-278-6308 (text and voice to Mitch)
877-228-7768 (customer support - support@catprint.com)

Lets help each other get email under control.
Unless it's an urgent email I process messages once a day.
I also am trying where practical to follow this concept:
http://five.sentenc.es/
For other great ideas see:  GTD
<http://www.43folders.com/2004/09/08/getting-started-with-getting-things-done>,
and 43Folders <http://www.43folders.com/howto>

*For urgent email please include URGENT in the subject.*

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#119

**Pull request merged**
