### PR TITLE
JSX Support

### PR DESCRIPTION
**Pull request by zetachang**
## Usage

Add `.jsx` to file which have JSX fragment.

``` ruby
class Fancy
  def render
    React.create_element('div') { "fancy" }
  end
end

class App
  include React::Component

  def render
    jsx(%x{
      <div>
        <h1>Outer</h1>
        <Fancy>{ #{5.times.to_a.join(",")} }</Fancy>
      </div>
    })
  end
end

React.expose_native_class(Fancy)

React.render React.create_element(App), `document.body`
```
## JSX Transformer

[Sprockets ES6](https://github.com/josh/sprockets-es6) is added as dependency to transform `.jsx` file to vanilla JavaScript (only [React transformer](http://babeljs.io/docs/usage/transformers/other/react/) is used) 
## React.expose_native_class

Since JSX needs a reference to component class in global scope, this helper method is added.

### CODE REVIEW

**Comment by zetachang** [comment]
Maybe add a method to get the native component class, and let user assign them to whatever scope they want may be a better idea.

```ruby
`var App = #{React.native_class(App)}`
React.render React.create_element(`<App />`), `document.body`
```

**Comment by adambeynon** [comment]
@zetachang what is the status of this? Anything I can help with/test/etc?

**Comment by zetachang** [comment]
@adambeynon , it's ready to get merged. The only concern is that I am not sure if this actually feed the need of someones who brought this up in #8.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#11

**Pull request merged**
